<!DOCTYPE html>
<html>
<head>
    <!-- Importing the Ext JS library -->
     <link href="https://cdnjs.cloudflare.com/ajax/libs/extjs/6.0.0/classic/theme-classic/resources/theme-classic-all.css" rel="stylesheet" />
      <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/extjs/6.0.0/ext-all.js"></script>

    <!-- Importando las clase necesarias para la construccion de nuestra Api -->
    <link rel="stylesheet" type="text/css" href="resource/css/main.css">
    <script type="text/javascript" src="application/app.js"></script>

    <!-- Favicon de alegra -->
    <link rel="shortcut icon" href="resource/img/imf.png" type="image/ico" />
    
    <title>Alegra App</title>
</head>
<body>
</body>
</html>